"""initial schema

Revision ID: 12916f19acec
Revises: 
Create Date: 2026-08-09 08:10:24.909701
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '12916f19acec'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_meta',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_app_meta'))
    )
    op.create_table('sync_outbox',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('target_type', sa.String(), nullable=False),
    sa.Column('target_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('next_retry_at', sa.String(), nullable=True),
    sa.Column('last_error', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sync_outbox')),
    sa.UniqueConstraint('target_type', 'target_id', name='uq_sync_outbox_target')
    )
    with op.batch_alter_table('sync_outbox', schema=None) as batch_op:
        batch_op.create_index('idx_sync_outbox_retry', ['next_retry_at'], unique=False)

    op.create_table('sync_state',
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('remote_revision', sa.Integer(), nullable=False),
    sa.Column('last_sync_at', sa.String(), nullable=True),
    sa.Column('last_hash', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('source_type', 'source_id', name=op.f('pk_sync_state'))
    )
    op.create_table('units',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('is_active', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.CheckConstraint('is_active IN (0, 1)', name=op.f('ck_units_units_active_bool')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_units')),
    sa.UniqueConstraint('code', name=op.f('uq_units_code'))
    )
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_code', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('is_system_admin', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.CheckConstraint('is_active IN (0, 1)', name=op.f('ck_users_users_active_bool')),
    sa.CheckConstraint('is_system_admin IN (0, 1)', name=op.f('ck_users_users_system_admin_bool')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('user_code', name=op.f('uq_users_user_code'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('idx_users_active', ['is_active'], unique=False)

    op.create_table('calendar_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('start_at', sa.String(), nullable=False),
    sa.Column('end_at', sa.String(), nullable=True),
    sa.Column('visibility', sa.String(), nullable=False),
    sa.Column('memo', sa.String(), nullable=True),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.CheckConstraint("event_type IN ('MEETING', 'ABSENCE', 'OTHER')", name=op.f('ck_calendar_events_calendar_events_type')),
    sa.CheckConstraint("visibility IN ('PRIVATE', 'TEAM')", name=op.f('ck_calendar_events_calendar_events_visibility')),
    sa.CheckConstraint('end_at IS NULL OR end_at >= start_at', name=op.f('ck_calendar_events_calendar_events_period')),
    sa.CheckConstraint('is_deleted IN (0, 1)', name=op.f('ck_calendar_events_calendar_events_deleted_bool')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_calendar_events_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_calendar_events'))
    )
    with op.batch_alter_table('calendar_events', schema=None) as batch_op:
        batch_op.create_index('idx_calendar_user_period', ['user_id', 'start_at', 'end_at'], unique=False)
        batch_op.create_index('idx_calendar_visibility_start', ['visibility', 'start_at'], unique=False)

    op.create_table('devices',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('device_name', sa.String(), nullable=True),
    sa.Column('is_current', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('last_seen_at', sa.String(), nullable=True),
    sa.CheckConstraint('is_current IN (0, 1)', name=op.f('ck_devices_devices_current_bool')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_devices_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_devices'))
    )
    op.create_table('personal_notes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('is_pinned', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.Column('is_deleted', sa.Integer(), nullable=False),
    sa.CheckConstraint('is_deleted IN (0, 1)', name=op.f('ck_personal_notes_personal_notes_deleted_bool')),
    sa.CheckConstraint('is_pinned IN (0, 1)', name=op.f('ck_personal_notes_personal_notes_pinned_bool')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_personal_notes_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_personal_notes'))
    )
    with op.batch_alter_table('personal_notes', schema=None) as batch_op:
        batch_op.create_index('idx_personal_notes_user_pin', ['user_id', 'is_pinned', 'updated_at'], unique=False)

    op.create_table('projects',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('planned_start', sa.String(), nullable=True),
    sa.Column('planned_end', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.CheckConstraint('is_deleted IN (0, 1)', name=op.f('ck_projects_projects_deleted_bool')),
    sa.CheckConstraint('planned_end IS NULL OR planned_start IS NULL OR planned_end >= planned_start', name=op.f('ck_projects_projects_period')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_projects_updated_by_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects'))
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index('idx_projects_period', ['planned_start', 'planned_end'], unique=False)
        batch_op.create_index('idx_projects_status', ['status'], unique=False)

    op.create_table('parts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('planned_start', sa.String(), nullable=True),
    sa.Column('planned_end', sa.String(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.CheckConstraint('is_deleted IN (0, 1)', name=op.f('ck_parts_parts_deleted_bool')),
    sa.CheckConstraint('planned_end IS NULL OR planned_start IS NULL OR planned_end >= planned_start', name=op.f('ck_parts_parts_period')),
    sa.CheckConstraint('weight > 0 AND weight <= 1', name=op.f('ck_parts_parts_weight')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_parts_project_id_projects'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_parts'))
    )
    with op.batch_alter_table('parts', schema=None) as batch_op:
        batch_op.create_index('idx_parts_project_sort', ['project_id', 'sort_order'], unique=False)

    op.create_table('project_editors',
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_project_editors_project_id_projects'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_project_editors_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('project_id', 'user_id', name=op.f('pk_project_editors'))
    )
    op.create_table('work_items',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('part_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('total_quantity', sa.Float(), nullable=False),
    sa.Column('unit_id', sa.String(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('planned_start', sa.String(), nullable=True),
    sa.Column('planned_end', sa.String(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.CheckConstraint('is_deleted IN (0, 1)', name=op.f('ck_work_items_work_items_deleted_bool')),
    sa.CheckConstraint('planned_end IS NULL OR planned_start IS NULL OR planned_end >= planned_start', name=op.f('ck_work_items_work_items_period')),
    sa.CheckConstraint('total_quantity >= 0', name=op.f('ck_work_items_work_items_total_quantity')),
    sa.CheckConstraint('weight > 0 AND weight <= 1', name=op.f('ck_work_items_work_items_weight')),
    sa.ForeignKeyConstraint(['part_id'], ['parts.id'], name=op.f('fk_work_items_part_id_parts'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], name=op.f('fk_work_items_unit_id_units'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_work_items'))
    )
    with op.batch_alter_table('work_items', schema=None) as batch_op:
        batch_op.create_index('idx_work_items_part_sort', ['part_id', 'sort_order'], unique=False)

    op.create_table('assignments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('work_item_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('allocated_quantity', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('is_deleted', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.CheckConstraint('allocated_quantity >= 0', name=op.f('ck_assignments_assignments_allocated_quantity')),
    sa.CheckConstraint('is_deleted IN (0, 1)', name=op.f('ck_assignments_assignments_deleted_bool')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_assignments_user_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['work_item_id'], ['work_items.id'], name=op.f('fk_assignments_work_item_id_work_items'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assignments')),
    sa.UniqueConstraint('work_item_id', 'user_id', name='uq_assignments_work_item_user')
    )
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.create_index('idx_assignments_user', ['user_id'], unique=False)
        batch_op.create_index('idx_assignments_work_item', ['work_item_id'], unique=False)

    op.create_table('assignment_progress',
    sa.Column('assignment_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('schedule_start', sa.String(), nullable=True),
    sa.Column('schedule_end', sa.String(), nullable=True),
    sa.Column('completed_quantity', sa.Float(), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.Column('device_id', sa.String(), nullable=True),
    sa.CheckConstraint('completed_quantity >= 0', name=op.f('ck_assignment_progress_assignment_progress_completed_quantity')),
    sa.CheckConstraint('schedule_end IS NULL OR schedule_start IS NULL OR schedule_end >= schedule_start', name=op.f('ck_assignment_progress_assignment_progress_period')),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.id'], name=op.f('fk_assignment_progress_assignment_id_assignments'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_assignment_progress_device_id_devices'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_assignment_progress_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('assignment_id', name=op.f('pk_assignment_progress'))
    )
    with op.batch_alter_table('assignment_progress', schema=None) as batch_op:
        batch_op.create_index('idx_assignment_progress_user', ['user_id'], unique=False)

    op.create_table('progress_history',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('assignment_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('previous_quantity', sa.Float(), nullable=False),
    sa.Column('delta_quantity', sa.Float(), nullable=False),
    sa.Column('current_quantity', sa.Float(), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('device_id', sa.String(), nullable=True),
    sa.CheckConstraint('current_quantity >= 0', name=op.f('ck_progress_history_progress_history_current_quantity')),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.id'], name=op.f('fk_progress_history_assignment_id_assignments'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_progress_history_device_id_devices'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_progress_history_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_progress_history'))
    )
    with op.batch_alter_table('progress_history', schema=None) as batch_op:
        batch_op.create_index('idx_progress_history_assignment_time', ['assignment_id', 'created_at'], unique=False)
        batch_op.create_index('idx_progress_history_user_time', ['user_id', 'created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('progress_history', schema=None) as batch_op:
        batch_op.drop_index('idx_progress_history_user_time')
        batch_op.drop_index('idx_progress_history_assignment_time')

    op.drop_table('progress_history')
    with op.batch_alter_table('assignment_progress', schema=None) as batch_op:
        batch_op.drop_index('idx_assignment_progress_user')

    op.drop_table('assignment_progress')
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.drop_index('idx_assignments_work_item')
        batch_op.drop_index('idx_assignments_user')

    op.drop_table('assignments')
    with op.batch_alter_table('work_items', schema=None) as batch_op:
        batch_op.drop_index('idx_work_items_part_sort')

    op.drop_table('work_items')
    op.drop_table('project_editors')
    with op.batch_alter_table('parts', schema=None) as batch_op:
        batch_op.drop_index('idx_parts_project_sort')

    op.drop_table('parts')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index('idx_projects_status')
        batch_op.drop_index('idx_projects_period')

    op.drop_table('projects')
    with op.batch_alter_table('personal_notes', schema=None) as batch_op:
        batch_op.drop_index('idx_personal_notes_user_pin')

    op.drop_table('personal_notes')
    op.drop_table('devices')
    with op.batch_alter_table('calendar_events', schema=None) as batch_op:
        batch_op.drop_index('idx_calendar_visibility_start')
        batch_op.drop_index('idx_calendar_user_period')

    op.drop_table('calendar_events')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('idx_users_active')

    op.drop_table('users')
    op.drop_table('units')
    op.drop_table('sync_state')
    with op.batch_alter_table('sync_outbox', schema=None) as batch_op:
        batch_op.drop_index('idx_sync_outbox_retry')

    op.drop_table('sync_outbox')
    op.drop_table('app_meta')
    # ### end Alembic commands ###
